apiVersion: apps/v1
kind: Deployment  
metadata:
  name: ad-ltigenie-dep
  labels:
    app: ad-ltigenie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-ltigenie
  template:
    metadata:
      labels:
        app: ad-ltigenie
    spec:
      containers:
      - name: ad-ltigenie-container
        image: ltimacrdemo.azurecr.io/acr-ltimgenie-ad:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080